---
title: "Fruits Example"
author: "Mara Averick"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Chart with keyboard navigation enabled taken from [{highcharter} issue #707](https://github.com/jbkunst/highcharter/issues/707)

# Highcharts Test

Here is [something focusable](#)

```{r}
library(highcharter)

data <- data.frame(
    fruit = c("apple", "banana", "orange", "pear"),
    count = c(2, 3, 5, 4)
    )

highchart() %>%
  hc_add_dependency(name = "modules/accessibility.js") %>%
  hc_add_dependency(name = "modules/exporting.js") %>%
  hc_add_dependency(name = "modules/export-data.js") %>%
  hc_title(text = "Fruits") %>%
  hc_xAxis(categories = data$fruit) %>%
  hc_add_series(
    data = data$count,
    type = "column",
    name = "Count"
  ) %>%
  hc_exporting(
    enabled = TRUE,
    accessibility = list(
      enabled = TRUE
    )
  ) %>%
    hc_plotOptions(
      accessibility = list(
        enabled = TRUE,
        keyboardNavigation = list(enabled = TRUE)
    )
  )
```


<button>Button</button>  
